export const stocks = [
    {
        id: '1_1_1',
        name: 'Apple Inc.',
        category: 'Large Cap',
        type: 'Technology',
        price: 150,
        todayHigh: 155,
        todayLow: 148,
        totalMarketCap: 2500000000000,
        isPurchased: true,
        purchasePrice: 160, // Example purchase price
        currentPrice: 180, // Example current price
        quantity: 100, // Example quantity
        profitLossPercentage: ((180 - 160) / 160) * 100, // Example profit/loss percentage
    },
    {
        id: '1_1_2',
        name: 'Microsoft Corp.',
        category: 'Large Cap',
        type: 'Technology',
        price: 280,
        todayHigh: 285,
        todayLow: 275,
        totalMarketCap: 2200000000000,
        isPurchased: false,
        purchasePrice: null,
        currentPrice: null,
        quantity: null,
        profitLossPercentage: null,
    },
    {
        id: '1_1_3',
        name: 'Amazon.com Inc.',
        category: 'Large Cap',
        type: 'E-commerce',
        price: 3400,
        todayHigh: 3450,
        todayLow: 3350,
        totalMarketCap: 1700000000000,
        isPurchased: false,
        purchasePrice: null,
        currentPrice: null,
        quantity: null,
        profitLossPercentage: null,
    },
    {
        id: '1_2_1',
        name: 'Square Inc.',
        category: 'Mid Cap',
        type: 'Financial Technology',
        price: 100,
        todayHigh: 105,
        todayLow: 98,
        totalMarketCap: 60000000000,
        isPurchased: false,
        purchasePrice: null,
        currentPrice: null,
        quantity: null,
        profitLossPercentage: null,
    },
    {
        id: '1_2_2',
        name: 'Spotify Technology',
        category: 'Mid Cap',
        type: 'Entertainment',
        price: 300,
        todayHigh: 310,
        todayLow: 295,
        totalMarketCap: 60000000000,
        isPurchased: true,
        purchasePrice: 280,
        currentPrice: 320,
        quantity: 200,
        profitLossPercentage: ((320 - 280) / 280) * 100,
    },
    {
        id: '1_2_3',
        name: 'Roku Inc.',
        category: 'Mid Cap',
        type: 'Entertainment',
        price: 350,
        todayHigh: 360,
        todayLow: 340,
        totalMarketCap: 45000000000,
        isPurchased: true,
        purchasePrice: 360,
        currentPrice: 380,
        quantity: 150,
        profitLossPercentage: ((380 - 360) / 360) * 100,
    },
    {
        id: '1_3_1',
        name: 'Plug Power Inc.',
        category: 'Small Cap',
        type: 'Energy',
        price: 25,
        todayHigh: 27,
        todayLow: 24,
        totalMarketCap: 15000000000,
        isPurchased: false,
        purchasePrice: null,
        currentPrice: null,
        quantity: null,
        profitLossPercentage: null,
    },
    {
        id: '1_3_2',
        name: 'SunPower Corp.',
        category: 'Small Cap',
        type: 'Energy',
        price: 22,
        todayHigh: 23,
        todayLow: 21,
        totalMarketCap: 4000000000,
        isPurchased: true,
        purchasePrice: 20,
        currentPrice: 25,
        quantity: 300,
        profitLossPercentage: ((25 - 20) / 20) * 100,
    },
    {
        id: '1_3_3',
        name: 'Blink Charging Co.',
        category: 'Small Cap',
        type: 'Energy',
        price: 30,
        todayHigh: 32,
        todayLow: 29,
        totalMarketCap: 1200000000,
        isPurchased: false,
        purchasePrice: null,
        currentPrice: null,
        quantity: null,
        profitLossPercentage: null,
    },
];

export const menu = [{
    id: '1',
    name: 'View stocks',
    items: stocks,
},
{
    id: '2',
    name: 'Transactions',
    items: [{
        id: '2_1',
        name: 'Purchase',
        disabled: false,
    }, {
        id: '2_2',
        name: 'Sell',
        disabled: true,
    }]
},
{
    id: '3',
    name: 'Account Details',
    items: [{
        id: '3_1',
        name: 'User Name',
    },
    {
        id: '3_2',
        name: 'PAN Number',
    }]
}];