export const stocks = [
    { id: 1, symbol: "AAPL", companyName: "Apple Inc.", price: 150.25, change: 1.20, marketCap: "2.5T", sectorId: 3 },
    { id: 2, symbol: "GOOGL", companyName: "Alphabet Inc.", price: 2700.00, change: -15.75, marketCap: "1.8T", sectorId: 2 },
    { id: 3, symbol: "AMZN", companyName: "Amazon.com Inc.", price: 3300.45, change: -20.50, marketCap: "1.6T", sectorId: 1 },
    { id: 4, symbol: "MSFT", companyName: "Microsoft Corp.", price: 290.15, change: 3.10, marketCap: "2.2T", sectorId: 11 },
    { id: 5, symbol: "TSLA", companyName: "Tesla Inc.", price: 720.50, change: 5.35, marketCap: "720B", sectorId: 10 },
    { id: 6, symbol: "FB", companyName: "Meta Platforms Inc.", price: 330.40, change: -2.40, marketCap: "900B", sectorId: 9 },
    { id: 7, symbol: "NFLX", companyName: "Netflix Inc.", price: 590.00, change: -10.50, marketCap: "260B", sectorId: 8 },
    { id: 8, symbol: "NVDA", companyName: "NVIDIA Corp.", price: 190.85, change: 4.70, marketCap: "480B", sectorId: 7 },
    { id: 9, symbol: "BRK.B", companyName: "Berkshire Hathaway Inc.", price: 285.60, change: 2.85, marketCap: "680B", sectorId: 6 },
    { id: 10, symbol: "V", companyName: "Visa Inc.", price: 225.35, change: 1.50, marketCap: "460B", sectorId: 5 },
    { id: 11, symbol: "JPM", companyName: "JPMorgan Chase & Co.", price: 158.20, change: -1.20, marketCap: "480B", sectorId: 4 },
    { id: 12, symbol: "JNJ", companyName: "Johnson & Johnson", price: 165.40, change: 0.85, marketCap: "430B", sectorId: 3 },
    { id: 13, symbol: "WMT", companyName: "Walmart Inc.", price: 145.60, change: -0.70, marketCap: "400B", sectorId: 2 },
    { id: 14, symbol: "PG", companyName: "Procter & Gamble Co.", price: 139.80, change: 1.20, marketCap: "350B", sectorId: 1 },
    { id: 15, symbol: "DIS", companyName: "The Walt Disney Company", price: 180.50, change: -3.10, marketCap: "330B", sectorId: 11 },
    { id: 16, symbol: "VZ", companyName: "Verizon Communications Inc.", price: 59.60, change: 0.40, marketCap: "250B", sectorId: 10 },
    { id: 17, symbol: "PFE", companyName: "Pfizer Inc.", price: 44.80, change: -0.50, marketCap: "220B", sectorId: 9 },
    { id: 18, symbol: "KO", companyName: "The Coca-Cola Company", price: 54.30, change: 0.75, marketCap: "230B", sectorId: 8 },
    { id: 19, symbol: "CSCO", companyName: "Cisco Systems Inc.", price: 52.60, change: 1.10, marketCap: "220B", sectorId: 7 },
    { id: 20, symbol: "PEP", companyName: "PepsiCo Inc.", price: 155.20, change: 2.20, marketCap: "210B", sectorId: 6 },
    { id: 21, symbol: "INTC", companyName: "Intel Corporation", price: 60.80, change: 0.80, marketCap: "250B", sectorId: 5 },
    { id: 22, symbol: "MRK", companyName: "Merck & Co., Inc.", price: 78.60, change: 0.70, marketCap: "200B", sectorId: 4 },
    { id: 23, symbol: "T", companyName: "AT&T Inc.", price: 29.40, change: -0.30, marketCap: "210B", sectorId: 3 },
    { id: 24, symbol: "CVX", companyName: "Chevron Corporation", price: 105.40, change: 1.60, marketCap: "220B", sectorId: 2 },
    { id: 25, symbol: "MCD", companyName: "McDonald's Corporation", price: 230.70, change: 2.10, marketCap: "190B", sectorId: 1 },
];

export const sectors = [
    { ID: 1, Name: "Technology" },
    { ID: 2, Name: "Consumer Electronics" },
    { ID: 3, Name: "E-Commerce" },
    { ID: 4, Name: "Automotive" },
    { ID: 5, Name: "Financials" },
    { ID: 6, Name: "Healthcare" },
    { ID: 7, Name: "Consumer Goods" },
    { ID: 8, Name: "Entertainment" },
    { ID: 9, Name: "Home Improvement" },
    { ID: 10, Name: "Telecommunications" },
    { ID: 11, Name: "Energy" }
];