const states = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
];

const products = [{
    ID: 1,
    Name: 'HD Video Player',
    Price: 330,
    Current_Inventory: 225,
    Backorder: 0,
    Manufacturing: 10,
    Category: 'Video Players',
}, {
    ID: 2,
    Name: 'SuperHD Player',
    Price: 400,
    Current_Inventory: 150,
    Backorder: 0,
    Manufacturing: 25,
    Category: 'Video Players',
}, {
    ID: 3,
    Name: 'SuperPlasma 50',
    Price: 2400,
    Current_Inventory: 0,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
}, {
    ID: 4,
    Name: 'SuperLED 50',
    Price: 1600,
    Current_Inventory: 77,
    Backorder: 0,
    Manufacturing: 55,
    Category: 'Televisions',
}, {
    ID: 5,
    Name: 'SuperLED 42',
    Price: 1450,
    Current_Inventory: 445,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
}, {
    ID: 6,
    Name: 'SuperLCD 55',
    Price: 1350,
    Current_Inventory: 345,
    Backorder: 0,
    Manufacturing: 5,
    Category: 'Televisions',
}, {
    ID: 7,
    Name: 'SuperLCD 42',
    Price: 1200,
    Current_Inventory: 210,
    Backorder: 0,
    Manufacturing: 20,
    Category: 'Televisions',
}, {
    ID: 8,
    Name: 'SuperPlasma 65',
    Price: 3500,
    Current_Inventory: 0,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
}, {
    ID: 9,
    Name: 'SuperLCD 70',
    Price: 4000,
    Current_Inventory: 95,
    Backorder: 0,
    Manufacturing: 5,
    Category: 'Televisions',
}, {
    ID: 10,
    Name: 'DesktopLED 21',
    Price: 175,
    Current_Inventory: 0,
    Backorder: 425,
    Manufacturing: 75,
    Category: 'Monitors',
}, {
    ID: 11,
    Name: 'DesktopLED 19',
    Price: 165,
    Current_Inventory: 425,
    Backorder: 0,
    Manufacturing: 110,
    Category: 'Monitors',
}, {
    ID: 12,
    Name: 'DesktopLCD 21',
    Price: 170,
    Current_Inventory: 210,
    Backorder: 0,
    Manufacturing: 60,
    Category: 'Monitors',
}, {
    ID: 13,
    Name: 'DesktopLCD 19',
    Price: 160,
    Current_Inventory: 150,
    Backorder: 0,
    Manufacturing: 210,
    Category: 'Monitors',
}, {
    ID: 14,
    Name: 'Projector Plus',
    Price: 550,
    Current_Inventory: 0,
    Backorder: 55,
    Manufacturing: 10,
    Category: 'Projectors',
}, {
    ID: 15,
    Name: 'Projector PlusHD',
    Price: 750,
    Current_Inventory: 110,
    Backorder: 0,
    Manufacturing: 90,
    Category: 'Projectors',
}, {
    ID: 16,
    Name: 'Projector PlusHT',
    Price: 1050,
    Current_Inventory: 0,
    Backorder: 75,
    Manufacturing: 57,
    Category: 'Projectors',
}, {
    ID: 17,
    Name: 'ExcelRemote IR',
    Price: 150,
    Current_Inventory: 650,
    Backorder: 0,
    Manufacturing: 190,
    Category: 'Automation',
}, {
    ID: 18,
    Name: 'ExcelRemote BT',
    Price: 180,
    Current_Inventory: 310,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Automation',
}, {
    ID: 19,
    Name: 'ExcelRemote IP',
    Price: 200,
    Current_Inventory: 0,
    Backorder: 325,
    Manufacturing: 225,
    Category: 'Automation',
}];


export { states, products };