export const countries = [
    { id: 1, name: "Afghanistan", dialCode: "+93", pattern: /^(\d{7,8})$/ },
    { id: 2, name: "Albania", dialCode: "+355", pattern: /^(\d{6,7})$/ },
    { id: 3, name: "Algeria", dialCode: "+213", pattern: /^(\d{9})$/ },
    { id: 4, name: "Andorra", dialCode: "+376", pattern: /^(\d{6})$/ },
    { id: 5, name: "Angola", dialCode: "+244", pattern: /^(\d{9})$/ },
    { id: 6, name: "Antigua and Barbuda", dialCode: "+1-268", pattern: /^(\d{7})$/ },
    { id: 7, name: "Argentina", dialCode: "+54", pattern: /^(\d{8,12})$/ },
    { id: 8, name: "Armenia", dialCode: "+374", pattern: /^(\d{7,8})$/ },
    { id: 9, name: "Australia", dialCode: "+61", pattern: /^([1-9])\d{8}$/ },
    { id: 10, name: "Austria", dialCode: "+43", pattern: /^(\d{4,13})$/ },
    { id: 11, name: "Azerbaijan", dialCode: "+994", pattern: /^(\d{7,9})$/ },
    { id: 12, name: "Bahamas", dialCode: "+1-242", pattern: /^(\d{7})$/ },
    { id: 13, name: "Bahrain", dialCode: "+973", pattern: /^(\d{7})$/ },
    { id: 14, name: "Bangladesh", dialCode: "+880", pattern: /^([6-9])\d{9}$/ },
    { id: 15, name: "Barbados", dialCode: "+1-246", pattern: /^(\d{7})$/ },
    { id: 16, name: "Belarus", dialCode: "+375", pattern: /^(\d{9})$/ },
    { id: 17, name: "Belgium", dialCode: "+32", pattern: /^(\d{6,8})$/ },
    { id: 18, name: "Belize", dialCode: "+501", pattern: /^(\d{7})$/ },
    { id: 19, name: "Benin", dialCode: "+229", pattern: /^(\d{7,8})$/ },
    { id: 20, name: "Bhutan", dialCode: "+975", pattern: /^([1-9])\d{7}$/ },
    { id: 21, name: "Bolivia", dialCode: "+591", pattern: /^(\d{7,8})$/ },
    { id: 22, name: "Bosnia and Herzegovina", dialCode: "+387", pattern: /^(\d{8,9})$/ },
    { id: 23, name: "Botswana", dialCode: "+267", pattern: /^(\d{7})$/ },
    { id: 24, name: "Brazil", dialCode: "+55", pattern: /^(\d{10,11})$/ },
    { id: 25, name: "Brunei", dialCode: "+673", pattern: /^(\d{7})$/ },
    { id: 26, name: "Bulgaria", dialCode: "+359", pattern: /^(\d{6,9})$/ },
    { id: 27, name: "Burkina Faso", dialCode: "+226", pattern: /^(\d{8})$/ },
    { id: 28, name: "Burundi", dialCode: "+257", pattern: /^(\d{8})$/ },
    { id: 29, name: "Cambodia", dialCode: "+855", pattern: /^(\d{8,9})$/ },
    { id: 30, name: "Cameroon", dialCode: "+237", pattern: /^(\d{8,9})$/ },
    { id: 31, name: "Canada", dialCode: "+1", pattern: /^(?:(?:\+|00)1)?[2-9]\d{9}$/ },
    { id: 32, name: "Cape Verde", dialCode: "+238", pattern: /^(\d{7})$/ },
    { id: 33, name: "Central African Republic", dialCode: "+236", pattern: /^(\d{8})$/ },
    { id: 34, name: "Chad", dialCode: "+235", pattern: /^(\d{7})$/ },
    { id: 35, name: "Chile", dialCode: "+56", pattern: /^(\d{8,9})$/ },
    { id: 36, name: "China", dialCode: "+86", pattern: /^(\d{11})$/ },
    { id: 37, name: "Colombia", dialCode: "+57", pattern: /^(\d{10})$/ },
    { id: 38, name: "Comoros", dialCode: "+269", pattern: /^(\d{7})$/ },
    { id: 39, name: "Congo", dialCode: "+242", pattern: /^(\d{7})$/ },
    { id: 40, name: "Congo, Democratic Republic of the", dialCode: "+243", pattern: /^(\d{9})$/ },
    { id: 41, name: "Costa Rica", dialCode: "+506", pattern: /^(\d{8})$/ },
    { id: 42, name: "Croatia", dialCode: "+385", pattern: /^(\d{8,9})$/ },
    { id: 43, name: "Cuba", dialCode: "+53", pattern: /^(\d{8})$/ },
    { id: 44, name: "Cyprus", dialCode: "+357", pattern: /^(\d{8})$/ },
    { id: 45, name: "Czech Republic", dialCode: "+420", pattern: /^(\d{9})$/ },
    { id: 46, name: "Denmark", dialCode: "+45", pattern: /^(\d{8})$/ },
    { id: 47, name: "Djibouti", dialCode: "+253", pattern: /^(\d{6})$/ },
    { id: 48, name: "Dominica", dialCode: "+1-767", pattern: /^(\d{7})$/ },
    { id: 49, name: "Dominican Republic", dialCode: "+1-809", pattern: /^(\d{7})$/ },
    { id: 50, name: "Dominican Republic", dialCode: "+1-829", pattern: /^(\d{7})$/ },
    { id: 51, name: "Dominican Republic", dialCode: "+1-849", pattern: /^(\d{7})$/ },
    { id: 52, name: "East Timor", dialCode: "+670", pattern: /^(\d{7})$/ },
    { id: 53, name: "Ecuador", dialCode: "+593", pattern: /^(\d{9})$/ },
    { id: 54, name: "Egypt", dialCode: "+20", pattern: /^(\d{9,10})$/ },
    { id: 55, name: "El Salvador", dialCode: "+503", pattern: /^(\d{8})$/ },
    { id: 56, name: "Equatorial Guinea", dialCode: "+240", pattern: /^(\d{7,9})$/ },
    { id: 57, name: "Eritrea", dialCode: "+291", pattern: /^(\d{7})$/ },
    { id: 58, name: "Estonia", dialCode: "+372", pattern: /^(\d{7,8})$/ },
    { id: 59, name: "Ethiopia", dialCode: "+251", pattern: /^(\d{9})$/ },
    { id: 60, name: "Fiji", dialCode: "+679", pattern: /^(\d{7})$/ },
    { id: 61, name: "Finland", dialCode: "+358", pattern: /^(\d{5,12})$/ },
    { id: 62, name: "France", dialCode: "+33", pattern: /^(\d{9})$/ },
    { id: 63, name: "Gabon", dialCode: "+241", pattern: /^(\d{6})$/ },
    { id: 64, name: "Gambia", dialCode: "+220", pattern: /^(\d{6,7})$/ },
    { id: 65, name: "Georgia", dialCode: "+995", pattern: /^(\d{8,9})$/ },
    { id: 66, name: "Germany", dialCode: "+49", pattern: /^(\d{5,12})$/ },
    { id: 67, name: "Ghana", dialCode: "+233", pattern: /^(\d{9,10})$/ },
    { id: 68, name: "Greece", dialCode: "+30", pattern: /^(\d{10})$/ },
    { id: 69, name: "Grenada", dialCode: "+1-473", pattern: /^(\d{7})$/ },
    { id: 70, name: "Guatemala", dialCode: "+502", pattern: /^(\d{8})$/ },
    { id: 71, name: "Guinea", dialCode: "+224", pattern: /^(\d{8,9})$/ },
    { id: 72, name: "Guinea-Bissau", dialCode: "+245", pattern: /^(\d{7})$/ },
    { id: 73, name: "Guyana", dialCode: "+592", pattern: /^(\d{7})$/ },
    { id: 74, name: "Haiti", dialCode: "+509", pattern: /^(\d{8})$/ },
    { id: 75, name: "Honduras", dialCode: "+504", pattern: /^(\d{8})$/ },
    { id: 76, name: "Hungary", dialCode: "+36", pattern: /^(\d{8,9})$/ },
    { id: 77, name: "Iceland", dialCode: "+354", pattern: /^(\d{7,8})$/ },
    { id: 78, name: "India", dialCode: "+91", pattern: /^[6-9]\d{9}$/ },
    { id: 79, name: "Indonesia", dialCode: "+62", pattern: /^(\d{9,11})$/ },
    { id: 80, name: "Iran", dialCode: "+98", pattern: /^(\d{10,11})$/ },
    { id: 81, name: "Iraq", dialCode: "+964", pattern: /^(\d{10})$/ },
    { id: 82, name: "Ireland", dialCode: "+353", pattern: /^(\d{7,9})$/ },
    { id: 83, name: "Israel", dialCode: "+972", pattern: /^(\d{9})$/ },
    { id: 84, name: "Italy", dialCode: "+39", pattern: /^(\d{5,11})$/ },
    { id: 85, name: "Jamaica", dialCode: "+1-876", pattern: /^(\d{7})$/ },
    { id: 86, name: "Japan", dialCode: "+81", pattern: /^(\d{9,10})$/ },
    { id: 87, name: "Jordan", dialCode: "+962", pattern: /^(\d{7,8})$/ },
    { id: 88, name: "Kazakhstan", dialCode: "+7", pattern: /^(\d{10})$/ },
    { id: 89, name: "Kenya", dialCode: "+254", pattern: /^(\d{9})$/ },
    { id: 90, name: "Kiribati", dialCode: "+686", pattern: /^(\d{5})$/ },
    { id: 91, name: "Kuwait", dialCode: "+965", pattern: /^(\d{8})$/ },
    { id: 92, name: "Kyrgyzstan", dialCode: "+996", pattern: /^(\d{9})$/ },
    { id: 93, name: "Laos", dialCode: "+856", pattern: /^(\d{8,9})$/ },
    { id: 94, name: "Latvia", dialCode: "+371", pattern: /^(\d{8})$/ },
    { id: 95, name: "Lebanon", dialCode: "+961", pattern: /^(\d{7,8})$/ },
    { id: 96, name: "Lesotho", dialCode: "+266", pattern: /^(\d{8})$/ },
    { id: 97, name: "Liberia", dialCode: "+231", pattern: /^(\d{7,8})$/ },
    { id: 98, name: "Libya", dialCode: "+218", pattern: /^(\d{9,10})$/ },
    { id: 99, name: "Liechtenstein", dialCode: "+423", pattern: /^(\d{7})$/ },
    { id: 100, name: "Lithuania", dialCode: "+370", pattern: /^(\d{8})$/ },
    { id: 101, name: "Luxembourg", dialCode: "+352", pattern: /^(\d{6,9})$/ },
    { id: 102, name: "Madagascar", dialCode: "+261", pattern: /^(\d{9})$/ },
    { id: 103, name: "Malawi", dialCode: "+265", pattern: /^(\d{7,8})$/ },
    { id: 104, name: "Malaysia", dialCode: "+60", pattern: /^(\d{9,10})$/ },
    { id: 105, name: "Maldives", dialCode: "+960", pattern: /^(\d{7})$/ },
    { id: 106, name: "Mali", dialCode: "+223", pattern: /^(\d{8})$/ },
    { id: 107, name: "Malta", dialCode: "+356", pattern: /^(\d{8})$/ },
    { id: 108, name: "Marshall Islands", dialCode: "+692", pattern: /^(\d{7})$/ },
    { id: 109, name: "Mauritania", dialCode: "+222", pattern: /^(\d{8})$/ },
    { id: 110, name: "Mauritius", dialCode: "+230", pattern: /^(\d{7})$/ },
    { id: 111, name: "Mexico", dialCode: "+52", pattern: /^(\d{10,11})$/ },
    { id: 112, name: "Micronesia", dialCode: "+691", pattern: /^(\d{7})$/ },
    { id: 113, name: "Moldova", dialCode: "+373", pattern: /^(\d{8})$/ },
    { id: 114, name: "Monaco", dialCode: "+377", pattern: /^(\d{5,9})$/ },
    { id: 115, name: "Mongolia", dialCode: "+976", pattern: /^(\d{8,9})$/ },
    { id: 116, name: "Montenegro", dialCode: "+382", pattern: /^(\d{7,8})$/ },
    { id: 117, name: "Morocco", dialCode: "+212", pattern: /^(\d{9})$/ },
    { id: 118, name: "Mozambique", dialCode: "+258", pattern: /^(\d{8,9})$/ },
    { id: 119, name: "Myanmar", dialCode: "+95", pattern: /^(\d{8,9})$/ },
    { id: 120, name: "Namibia", dialCode: "+264", pattern: /^(\d{7,8})$/ },
    { id: 121, name: "Nauru", dialCode: "+674", pattern: /^(\d{7})$/ },
    { id: 122, name: "Nepal", dialCode: "+977", pattern: /^(\d{9})$/ },
    { id: 123, name: "Netherlands", dialCode: "+31", pattern: /^(\d{9,10})$/ },
    { id: 124, name: "New Zealand", dialCode: "+64", pattern: /^(\d{8,10})$/ },
    { id: 125, name: "Nicaragua", dialCode: "+505", pattern: /^(\d{8})$/ },
    { id: 126, name: "Niger", dialCode: "+227", pattern: /^(\d{8})$/ },
    { id: 127, name: "Nigeria", dialCode: "+234", pattern: /^(\d{10})$/ },
    { id: 128, name: "Norway", dialCode: "+47", pattern: /^(\d{8,9})$/ },
    { id: 129, name: "Oman", dialCode: "+968", pattern: /^(\d{7})$/ },
    { id: 130, name: "Pakistan", dialCode: "+92", pattern: /^(\d{10})$/ },
    { id: 131, name: "Palau", dialCode: "+680", pattern: /^(\d{7})$/ },
    { id: 132, name: "Palestine", dialCode: "+970", pattern: /^(5[0-9]{8})$/ },
    { id: 133, name: "Panama", dialCode: "+507", pattern: /^(6|7|8|9)\d{6}$/ },
    { id: 134, name: "Papua New Guinea", dialCode: "+675", pattern: /^(7|8)\d{7}$/ },
    { id: 135, name: "Paraguay", dialCode: "+595", pattern: /^(9[5-9])\d{7}$/ },
    { id: 136, name: "Peru", dialCode: "+51", pattern: /^(9[1-9])\d{7}$/ },
    { id: 137, name: "Philippines", dialCode: "+63", pattern: /^(9[0-9])\d{9}$/ },
    { id: 138, name: "Poland", dialCode: "+48", pattern: /^(5[0-9])\d{8}$/ },
    { id: 139, name: "Portugal", dialCode: "+351", pattern: /^(9[0-9])\d{7}$/ },
    { id: 140, name: "Qatar", dialCode: "+974", pattern: /^(5[0-9])\d{6}$/ },
    { id: 141, name: "Romania", dialCode: "+40", pattern: /^(7[2-8])\d{7}$/ },
    { id: 142, name: "Russia", dialCode: "+7", pattern: /^(9[0-9]{9})$/ },
    { id: 143, name: "Rwanda", dialCode: "+250", pattern: /^(7|8)\d{8}$/ },
    { id: 144, name: "Saint Kitts and Nevis", dialCode: "+1-869", pattern: /^(5|6|7|8|9)\d{6}$/ },
    { id: 145, name: "Saint Lucia", dialCode: "+1-758", pattern: /^(5|7|8)\d{6}$/ },
    { id: 146, name: "Saint Vincent and the Grenadines", dialCode: "+1-784", pattern: /^(4|7|9)\d{6}$/ },
    { id: 147, name: "Samoa", dialCode: "+685", pattern: /^(7|8)\d{6}$/ },
    { id: 148, name: "San Marino", dialCode: "+378", pattern: /^(6|9)\d{5}$/ },
    { id: 149, name: "Sao Tome and Principe", dialCode: "+239", pattern: /^(9[0-9]{7})$/ },
    { id: 150, name: "Saudi Arabia", dialCode: "+966", pattern: /^(5[0-9])\d{7}$/ },
    { id: 151, name: "Senegal", dialCode: "+221", pattern: /^(7[0-9])\d{7}$/ },
    { id: 152, name: "Serbia", dialCode: "+381", pattern: /^(6)\d{7,8}$/ },
    { id: 153, name: "Seychelles", dialCode: "+248", pattern: /^(2[5-7]|4[0-1])\d{4}$/ },
    { id: 154, name: "Sierra Leone", dialCode: "+232", pattern: /^(2[0-7]|3[0-9]|4[0-2])\d{5}$/ },
    { id: 155, name: "Singapore", dialCode: "+65", pattern: /^(8|9)\d{7}$/ },
    { id: 156, name: "Slovakia", dialCode: "+421", pattern: /^(9)\d{8}$/ },
    { id: 157, name: "Slovenia", dialCode: "+386", pattern: /^(3[0-9]|4[0-1])\d{5,7}$/ },
    { id: 158, name: "Solomon Islands", dialCode: "+677", pattern: /^(5|7|8)\d{5}$/ },
    { id: 159, name: "Somalia", dialCode: "+252", pattern: /^(6|9)\d{7}$/ },
    { id: 160, name: "South Africa", dialCode: "+27", pattern: /^(6|7|8)\d{8}$/ },
    { id: 161, name: "South Korea", dialCode: "+82", pattern: /^(10)\d{8}$/ },
    { id: 162, name: "South Sudan", dialCode: "+211", pattern: /^(9[0-9])\d{7}$/ },
    { id: 163, name: "Spain", dialCode: "+34", pattern: /^(6|7|9)\d{8}$/ },
    { id: 164, name: "Sri Lanka", dialCode: "+94", pattern: /^(7|9)\d{8}$/ },
    { id: 165, name: "Sudan", dialCode: "+249", pattern: /^(9)\d{8}$/ },
    { id: 166, name: "Suriname", dialCode: "+597", pattern: /^(6)\d{6}$/ },
    { id: 167, name: "Swaziland", dialCode: "+268", pattern: /^(7|9)\d{7}$/ },
    { id: 168, name: "Sweden", dialCode: "+46", pattern: /^(7|8)\d{8}$/ },
    { id: 169, name: "Switzerland", dialCode: "+41", pattern: /^(7|8|9)\d{8}$/ },
    { id: 170, name: "Syria", dialCode: "+963", pattern: /^(9[0-9])\d{7}$/ },
    { id: 171, name: "Taiwan", dialCode: "+886", pattern: /^(9)\d{8}$/ },
    { id: 172, name: "Tajikistan", dialCode: "+992", pattern: /^(9)\d{8}$/ },
    { id: 173, name: "Tanzania", dialCode: "+255", pattern: /^(6|7)\d{8}$/ },
    { id: 174, name: "Thailand", dialCode: "+66", pattern: /^(6|8|9)\d{8}$/ },
    { id: 175, name: "Timor-Leste", dialCode: "+670", pattern: /^(7)\d{7}$/ },
    { id: 176, name: "Togo", dialCode: "+228", pattern: /^(9)\d{7}$/ },
    { id: 177, name: "Tonga", dialCode: "+676", pattern: /^(7|8)\d{4}$/ },
    { id: 178, name: "Trinidad and Tobago", dialCode: "+1-868", pattern: /^(2|3|4|5|6|7)\d{6}$/ },
    { id: 179, name: "Tunisia", dialCode: "+216", pattern: /^(2|5|9)\d{7}$/ },
    { id: 180, name: "Turkey", dialCode: "+90", pattern: /^(5)\d{9}$/ },
    { id: 181, name: "Turkmenistan", dialCode: "+993", pattern: /^(6|7)\d{7}$/ },
    { id: 182, name: "Tuvalu", dialCode: "+688", pattern: /^(9)\d{4}$/ },
    { id: 183, name: "Uganda", dialCode: "+256", pattern: /^(7|4)\d{8}$/ },
    { id: 184, name: "Ukraine", dialCode: "+380", pattern: /^(39|50|63|66|67|68|73|89)\d{7}$/ },
    { id: 185, name: "United Arab Emirates", dialCode: "+971", pattern: /^(5)\d{8}$/ },
    { id: 186, name: "Uruguay", dialCode: "+598", pattern: /^(9)\d{7}$/ },
    { id: 187, name: "Uzbekistan", dialCode: "+998", pattern: /^(9)\d{8}$/ },
    { id: 188, name: "Vanuatu", dialCode: "+678", pattern: /^(5|7)\d{4}$/ },
    { id: 189, name: "Venezuela", dialCode: "+58", pattern: /^(4|5|6)\d{9}$/ },
    { id: 190, name: "Vietnam", dialCode: "+84", pattern: /^(3|5|7|8|9)\d{8}$/ },
    { id: 191, name: "Yemen", dialCode: "+967", pattern: /^(7)\d{8}$/ },
    { id: 192, name: "Zambia", dialCode: "+260", pattern: /^(9)\d{8}$/ },
    { id: 193, name: "Zimbabwe", dialCode: "+263", pattern: /^(7|7|8)\d{7}$/ },

];

export const genders = ["Male", "Female", "Other"];
